# Pizza API

## To use these HTTP endpoint install the REST Client plugin in VSCode.

GET https://pizza-api.projectcodex.net/api/pizzas

### create client cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=Nkosingiphile08

### Access user historical orders

GET https://pizza-api.projectcodex.net/api/pizza-cart/username/Nkosingiphile08

### get a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/8iRigRqd0G/get


### Add a pizza in the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json

{
    "cart_code": "8iRigRqd0G",
    "pizza_id": 17
}
  
### Add a pizza in the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json

{
    "cart_code": "8iRigRqd0G",
    "pizza_id": 11
}

### Featured pizzas
POST https://api/pizzas/featured?username=your_Nkosingiphile08


### Remove a pizza in the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
Content-Type: application/json

{
    "cart_code": "8iRigRqd0G",
    "pizza_id": 11
}

### get all the carts for a given user
GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=Nkosingiphile08


### get all active carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=Nkosingiphile08/active

### Pay for a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay
Content-Type: application/json

{
    "cart_code" : "8iRigRqd0G",
    "amount" : 60
}

### cart history
GET https://pizza-api.projectcodex.net/api/pizza-cart/username/Nkosingiphile08


POST https://pizza-api.projectcodex.net/api/pizzas/featured 
{
	username : "Nkosingiphile08", // Request failed
    pizza_id : 
}

### Accessing featured 
GET https://pizza-api.projectcodex.net/api/pizzas/featured?username=Nkosingiphile08