pizza API

## To use HTTP endpoint install the REST client plugin in VSCODE

GET https://pizza-api.projectcodex.net/api/pizzas

### create client cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=Nkosingiphile08

### get a cart

GET https://pizza-api.projectcodex.net/api/pizza-cart/ySTxAFwiQw/get


### Add a pizza in the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json

{
    "cart_code": "kehv4PcRKJ",
    "pizza_id": 10
}


### Add a pizza in the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/add
Content-Type: application/json

{
    "cart_code": "kehv4PcRKJ",
    "pizza_id": 11
}



### Remove a pizza in the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/remove
Content-Type: application/json

{
    "cart_code": "kehv4PcRKJ",
    "pizza_id": 11
}

### get all the carts for a given user
GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=Nkosingiphile08


### get all active carts for a given user

GET https://pizza-api.projectcodex.net/api/pizza-cart/create?username=Nkosingiphile08/active

### Pay for a pizza from the cart

POST https://pizza-api.projectcodex.net/api/pizza-cart/pay
Content-Type: application/json

{
    "cart_code" : "kehv4PcRKJ",
    "amount" : 50
}